spring:
  main:
    banner-mode: off

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
    com:
      thee5176:
        ledger_command:
          record:
            application:
              controller:
                LedgerController: DEBUG
            domain:
              service:
                LedgerCommandService: DEBUG
            infrastructure:
              repository:
                LedgerItemsRepository: ERROR
                LedgerRepository: ERROR
  file:
    name: logs/dev-logs.json
