name: Build and Run with Docker Compose

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:

jobs:
  build:
    name: Build and Run with Docker Compose
    runs-on: ubuntu-latest
    env:
      DB_USERNAME: ${{ vars.DB_USERNAME }}
      DB_PASSWORD: ${{ vars.DB_PASSWORD }}
      DB_NAME: ${{ vars.DB_NAME }}
      DB_URL: ${{ vars.DB_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Clean up Docker environment
        run: docker compose down -v --remove-orphans

      - name: Start database service
        run: docker compose up test_command_postgres -d
          
      - name: Wait for database to be ready
        run: |
          echo "Waiting for database connection..."
          until docker compose exec -T test_command_postgres pg_isready -U postgres; do
          sleep 2
          done
          echo "Database is ready."
          
      - name: Run Flyway migrations
        run: mvn flyway:migrate

      - name: Build application package
        run: mvn clean package

      - name: Build and run all services with Docker Compose
        run: docker compose up -d --build